version: '3'

tasks:
  develop:
    cmds:
      - cmd: go mod download
  docker:
    cmds:
      - cmd: docker rm $(docker stop $(docker ps -a -q --filter ancestor=directory-api)) || true
      - cmd: docker build -t directory-api .
      - cmd: docker compose up -d
  run:
    cmds:
      - cmd: CGO_ENABLED=0 go build -o directory-api
      - cmd: ./directory-api
